package com.library_database.library_app.Controller;

public enum AdminScenario {
    BOOK_CREATION_SUCCESS,
    BOOK_CREATION_FAILURE,
    LOAN_CREATION_SUCCESS,
    LOAN_CREATION_FAILURE,
    BOOK_REMOVAL_SUCCESS,
    BOOK_REMOVAL_FAILURE,
    LOAN_REMOVAL_SUCCESS,
    LOAN_REMOVAL_FAILURE,
    BOOK_EDIT_SUCCESS,
    BOOK_EDIT_FAILURE,
    LOAN_EDIT_SUCCESS,
    LOAN_EDIT_FAILURE,
    SEARCH_FAILURE,
    ACCOUNT_CREATE_SUCCESS,
    ACCOUNT_CREATE_FAILURE,
    ACCOUNT_REMOVAL_SUCCESS,
    ACCOUNT_REMOVAL_FAILURE,
    LOAN_ACCOUNT_EXIST,
    LOAN_ACCOUNT_ADMIN,
    LOAN_ID_MISMATCH
}
